// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvmrqcetviqfsuixctxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bXJxY2V0dmlxZnN1aXhjdHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDg1NTIsImV4cCI6MjA2MzQyNDU1Mn0.KBxCplTiDBVmSMvjjS88HeJIRpSRVsjDMBYefayV-oI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);